name: User Story
description: Describes a user story.
title: "<title>"
labels: [user story]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the user flow. / Keep it brief and simple.
      placeholder: What is the user supposed te be able to do? Why is this story revelant?
    validations:
      required: true

  - type: input
    id: who
    attributes:
      label: As
      description: Which kind of people will be concerned by this story?
      placeholder: ex. Smart Contract Developer
    validations:
      required: true

  - type: input
    id: what
    attributes:
      label: I want to
      description: As the target of this user story, what would I be able to do.
      placeholder: ex. make something with outcome
    validations:
      required: true

  - type: textarea
    id: DoD
    attributes:
      label: Definition of Done
      description: Describe step by step what should be done at the end.
      placeholder: Each checkboxes will later correspond to 'Task Issues'.
      value: |
        - [ ] 1. 
        - [ ] 2. 
        - [ ] 3.
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true