enum MessageType {
  GET_WALLETS = 'GET_WALLETS',
  WALLETS = 'WALLETS',
  GET_INTERACT_CONTRACTS = 'GET_INTERACT_CONTRACTS',
  INTERACT_CONTRACTS = 'INTERACT_CONTRACTS',
  GET_DEPLOY_CONTRACTS = 'GET_DEPLOY_CONTRACTS',
  DEPLOY_CONTRACTS = 'DEPLOY_CONTRACTS',
  WRITE = 'WRITE',
  WRITE_RESPONSE = 'WRITE_RESPONSE',
  READ = 'READ',
  GET_SCRIPTS = 'GET_SCRIPTS',
  SCRIPTS = 'SCRIPTS',
  GET_ENVIRONMENTS = 'GET_ENVIRONMENTS',
  ENVIRONMENTS = 'ENVIRONMENTS',
  READ_RESPONSE = 'READ_RESPONSE',
  DEPLOY_SCRIPT = 'DEPLOY_SCRIPT',
  DEPLOY_SCRIPT_RESPONSE = 'DEPLOY_SCRIPT_RESPONSE',
  DEPLOY_CONTRACT = 'DEPLOY_CONTRACT',
  DEPLOY_CONTRACT_RESPONSE = 'DEPLOY_CONTRACT_RESPONSE',
  DELETE_WALLET = 'DELETE_WALLET',
  EDIT_WALLET = 'EDIT_WALLET',
  DELETE_ENVIRONMENT = 'DELETE_ENVIRONMENT',
  EDIT_ENVIRONMENT = 'EDIT_ENVIRONMENT',
  DELETE_CONTRACT = 'DELETE_CONTRACT',
  EDIT_CONTRACT = 'EDIT_CONTRACT',
  OPEN_PANEL = 'OPEN_PANEL',
  UNKNOWN = 'UNKNOWN',
}

enum InputAction {
  ADD = 'Add',
  REMOVE = 'Remove',
}

export { MessageType, InputAction };
