name: Publish core

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      CARGO_REGISTRY_TOKEN:
        required: true
      VSCE_PAT:
        required: true

jobs:
  build-and-publish-core:
    name: Build and Publish Core
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1

      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: |
          bun install

      - name: Build
        run: |
          bun build

      - name: Publish
        run: |
          bun publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ inputs.CARGO_REGISTRY_TOKEN || secrets.CARGO_REGISTRY_TOKEN }}
          VSCE_PAT: ${{ inputs.VSCE_PAT || secrets.VSCE_PAT }}
  

