name: Publish extension

on:
  workflow_call:
    inputs:
      version: 
        description: 'Version of the extension'
        required: true
        type: string
      pre-release:
        description: 'Publish as a pre-release'
        required: false
        default: false
        type: boolean
    secrets:
      CARGO_REGISTRY_TOKEN:
        required: true
      VSCE_PAT:
        required: true

  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the extension'
        required: true
      pre-release:
        description: 'Publish as a pre-release'
        required: false
        default: false
        type: boolean

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            code-target: win32-x64
          #- os: windows-latest
          #  target: i686-pc-windows-msvc
          #  code-target: win32-ia32
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            code-target: win32-arm64
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            code-target: linux-x64
            #container: ubuntu:18.04
          #- os: ubuntu-20.04
          #  target: aarch64-unknown-linux-gnu
          #  code-target: linux-arm64
          #- os: ubuntu-20.04
          #  target: arm-unknown-linux-gnueabihf
          #  code-target: linux-armhf
          - os: macos-latest
            target: x86_64-apple-darwin
            code-target: darwin-x64
          - os: macos-latest
            target: aarch64-apple-darwin
            code-target: darwin-arm64
    uses: ./.github/workflows/publish-targeted-extension.yml
    with:
      os: ${{ matrix.os }}
      target: ${{ matrix.target }}
      code-target: ${{ matrix.code-target }}
      version: ${{ inputs.version }}
      pre-release: ${{ inputs.pre-release }}
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      VSCE_PAT: ${{ secrets.VSCE_PAT }}